Fix bower invocation
A bad `this` reference was causing `pulp dep` to fail with:
```
    this.launchBower(bowerArgs, callback);
         ^
TypeError: Object #<Object> has no method 'launchBower'
```